name:  Docker Image CI

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build and push iamge
        run: |
          DOCKER_NAME: docker-container
          DOCKER_IMAGE=docker.pkg.github.com/loiphamvn/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:${GITHUB_REF##*/} 
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
          docker build -f Dockerfile --pull -t $DOCKER_IMAGE . 
          docker push $DOCKER_IMAGE 
